name: cjamesonphotography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75
title: cj photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d3dee4'
    - '#a9bdc6'
    - '#1d302c'
    - '#6992a8'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
